services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    # aliases
    Jalismrs\Symfony\Bundle\JalismrsProcessBundle\ProcessManager: '@jalismrs_process.process_manager'
    
    # services
    jalismrs_process.process_manager:
        arguments:
            $cap: '%jalismrs_process.cap%'
        class: 'Jalismrs\Symfony\Bundle\JalismrsProcessBundle\ProcessManager'
